Check if con exists before querying submembers
On sway, sometimes there is no focused container returned (think it happens either before or after swaylock runs), so `con` is None.

```
>autotiling
Error: 'NoneType' object has no attribute 'floating'
```